#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'

# Variables
export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share
export BROWSER='firefox'
export EDITOR='nvim'

# Custom bash prompt via kirsle.net/wizards/ps1.html
export PS1="\[$(tput bold)\]\[$(tput setaf 1)\][\[$(tput setaf 3)\]\u\[$(tput setaf 2)\]@\[$(tput setaf 4)\]\h \[$(tput setaf 5)\]\W\[$(tput setaf 1)\]]\[$(tput setaf 7)\]\\$ \[$(tput sgr0)\]"
# Some aliases to make me type less
alias edmirror='sudo $EDITOR /etc/pacman.d/mirrorlist'
alias alcfg='$EDITOR $HOME/.config/alacritty/alacritty.yml'
alias qtilecfg='$EDITOR $HOME/.config/qtile/config.py'
alias vim='nvim'

# Path
PATH=$HOME/.cargo/bin:$HOME/.local/bin:$PATH

# iBus Settings
export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus

setxkbmap es
